package com.keyholesoftware.devops.dateservice;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import io.jaegertracing.Configuration;
import io.opentracing.Tracer;

@SpringBootApplication
public class DateServiceApplication {

	public static void main(String[] args) {
		SpringApplication.run(DateServiceApplication.class, args);
	}

	@Bean
	public Tracer jaegerTracer() {
		// The following environment variables need to set
		// JAEGER_SERVICE_NAME=simple-springboot-service
		// JAEGER_ENDPOINT="http://jaeger-collector.istio-system:14268/api/traces"
		// JAEGER_PROPAGATION="b3"
		// JAEGER_TRACEID_128BIT="true" Use 128bit tracer id to be compatible with the trace id generated by istio/envoy
		return Configuration.fromEnv().getTracer();
	}
}
